CREATE DATABASE Management_App;

CREATE TABLE Customer (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FirstName NVARCHAR(MAX) NOT NULL,
    LastName NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE [Order] (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    OrderDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18, 2) NOT NULL,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (CustomerId) REFERENCES Customer(Id)
);
GO

CREATE TABLE Product (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(MAX) NOT NULL,
    Price DECIMAL(18, 2) NOT NULL
);
GO

CREATE TABLE OrderItem (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18, 2) NOT NULL,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES [Order](Id),
    FOREIGN KEY (ProductId) REFERENCES Product(Id)
);
GO